### ISSUE TITLE
Random Service

### ISSUE THREAD

**Issue by umutphp** [ayse8888/random-quotes#1]
Why did you randomize the quotes on your own instead of using https://api.quotable.io/random?

https://github.com/ayse8888/random-quotes/blob/ef5cca9985d4fa6ad62e2e2440dfc1cec049493c/App.js#L13

**Comment by ayse8888** [comment]
I  checked the API documentation. And actually I was gonna use https://api.quotable.io/random at the beginning. But I saw that it returns only one quote and you can get the character number only. So I thought it would be more suitable to go with https://quotable.io/quotes since it was returning a list of quotes.

**Comment by umutphp** [comment]
@ayse8888 many thanks for the clarification. I could not get the point and the problem about getting a single quote, but It is not a big deal :).
